function cuadratura

figure('Name','Oscilator armonic in cuadratura',...
    'Units','normalized',...
    'Position',[ .01 .1 90 .81 ],...
    'NumberTitle','off','color',[0.3010, 0.7450, 0.9330]);

f=uimenu('Label','Documentatie');
uimenu(f,'Label','Foaie de capat',...
       'Callback','fcfoaie');% A string specifying the text label on the menu item. 
   uimenu(f,'Label','Cerinta',...
       'Callback','fccer');
   uimenu(f,'Label','Circuit',...
       'Callback','imagine');
   uimenu(f,'Label','Bibliografie',...
       'Callback','fcbiblio');
   uimenu(f,'Label','Documentatie',...
       'Callback', 'open(''doc.pdf'')')
   
   
   
   h1=uicontrol('Style','pushbutton',...   %creates a pushbutton
       'Units','normalized',...
       'Position',[.01 0.8 .18 .09],...
       'fontweight','bold',...
       'fontsize',15,...
       'String','Circuit',...
       'callback','imagine');
 pos1 = getpixelposition(h1);            %changes the position of the button with respect to the panel
setpixelposition(h1,pos1 + [10 10 25 25]);

    h2=uicontrol('Style','pushbutton',...   %creates a pushbutton
       'Units','normalized',...
       'Position',[.2 0.8 .18 .09],...
       'fontweight','bold',...
       'fontsize',15,...
       'String','Documentation',...
       'callback', 'open("doc.pdf")')
 pos1 = getpixelposition(h2);            %changes the position of the button with respect to the panel
setpixelposition(h2,pos1 + [10 10 25 25]);
    


%Objects for the resistance
%static text box
uicontrol('Style','text',...
'Units','normalized',...
'Position',[0.045 0.65 0.11 0.10],...
'fontweight','bold',...
'fontsize',12,...
'Backgroundcolor', 'w',...
'String','Value of Resistance[Ω]',...
'Callback','imagine');

%allow us to edit the value of resistance
p2=uicontrol('Style','edit',...
'Units','normalized',...
'Backgroundcolor', 'w',...
'Position',[0.045 0.66 0.11 0.05],...
'String','',...
'tag','primul');



%Objects for the capacitance
%control buttons
uicontrol('Style','text',...
'Units','normalized',...
'Position',[0.045 0.50 0.11 0.10],...
'fontweight','bold',...
'fontsize',12,...
'Backgroundcolor', 'w',...
'String','Value of Capacitance[u]');




p1=uicontrol('Style','edit',...
'Units','normalized',...
'Backgroundcolor', 'w',...
'Position',[0.045 0.51 0.11 0.05],...
'String',' ',...
'tag','primul');

%Objects for the number of periods
%control buttons
uicontrol('Style','text',...
'Units','normalized',...
'Position',[0.045 0.35 0.11 0.10],...
'fontweight','bold',...
'fontsize',12,...
'Backgroundcolor', 'w',...
'String','Number of periods');




p3=uicontrol('Style','edit',...
'Units','normalized',...
'Backgroundcolor', 'w',...
'Position',[0.045 0.36 0.11 0.05],...
'String',' ',...
'tag','primul');


%ax=axes('Units','normalized','Position',[0.54 0.4 0.42 0.55]);
%title('Semnalul de iesire')
%text('HorizontalAlignment','center')
uicontrol('Style','pushbutton','Units','normalized','String','Signal Vout1','Position',[0.01 0.15 0.1 0.1],'Callback',{@sinus_callback});
uicontrol('Style','pushbutton','Units','normalized','String','Signal Vout2','Position',[0.01 0.05 0.1 0.1],'Callback',{@si_callback});

function sinus_callback(source,eventdata)
N=str2double(get(p3,'String'));
R=str2double(get(p2,'String'));
C=str2double(get(p1,'String'));
f=1/2*pi*R*C;
T=1/f;
t=0:T/200:N*T;
sinus=sin((2*pi*f*t));
subplot(2,2,2);
axis equal
plot(t,sinus,...
    'color','blue');
title('Signal Vout2 Chronogram');
grid on
end




function si_callback(sourc,eventdat)
N=str2double(get(p3,'String'));
R=str2double(get(p2,'String'));
C=str2double(get(p1,'String'));
f=1/2*pi*R*C;
T=1/f;
t=0:T/200:N*T;
sinus=sin((2*pi*f*t)+pi/2);
subplot(2,2,4)
axis equal
plot(t,sinus,...
    'color','red');
title('Signal Vout2 Chronogram');
grid on
end

end