figure('Name','SWITCHING DR TWO-PORT NETWORKS',...
    'Units','normalized',...
    'Position',[ .001 .09 95 .81 ],...
    'NumberTitle','off','color','[0.4660 0.6740 0.1880]');
w = imread('1.jpg'); %reads the picture% 
imshow(w,'InitialMagnification',200) %displays the picture%

b1=uicontrol('Style','pushbutton',...   %creates a pushbutton for the first circuit
       'Units','normalized',...
        'Position',[.01 0.8 .40 .09],...
        'FontWeight','bold','Backgroundcolor','#808080',...
        'fontsize',15,...
        'String','Two-port DR network Circuit with output across R',...
        'callback','Circuit_1');

b2=uicontrol('Style','pushbutton',...   %creates a pushbutton for the second circuit
       'Units','normalized',...
        'Position',[.01 0.7 .40 .09],...
        'fontweight','bold','Backgroundcolor','#808080',...
        'fontsize',15,...
        'String','Two-port DR network Circuit with output across D',...
        'callback','Circuit_2');

b3=uicontrol('Style','pushbutton',...   %creates a pushbutton for closing the figure
       'Units','normalized',...
        'Position',[.01 0.005 .40 .09],...
        'FontWeight','bold','Backgroundcolor','#808080',...
        'fontsize',15,...
        'String','Close',...
        'callback','close(gcf)');

b4=uicontrol('Style','pushbutton',...   %creates a pushbutton for Opening the documentation
       'Units','normalized',...
        'Position',[.01 0.9 .40 .09],...
        'FontWeight','bold','Backgroundcolor','#808080',...
        'fontsize',15,...
        'String','Documentation',...
        'callback','Docx');

b5=uicontrol('Style','pushbutton',...   %creates a pushbutton for the Circuit in 3d format
       'Units','normalized',...
        'Position',[.01 0.6 .40 .09],...
        'FontWeight','bold','Backgroundcolor','#808080',...
        'fontsize',15,...
        'String','Two-port DR in 3D format illustration',...
        'callback','Circuit_3');


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Style','text',...  % creates a text for the Input Voltage
'Units','normalized',...
'Position',[0.15 0.40 0.11 0.10],...
'fontweight','bold',...
'fontsize',12,...
'Backgroundcolor', 'w',...
'String','Value for the AC Generator(V)');

v1=uicontrol('Style','edit',... % creates a bar for the Input Voltage
'Units','normalized',...
'Backgroundcolor', '#808080',...
'Position',[0.18 0.41 0.051 0.03],...
'String',' ',...
'tag','first');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

uicontrol('Style','text',...% creates a text for the Number of Period
'Units','normalized',...
'Position',[0.3 0.40 0.11 0.10],...
'fontweight','bold',...
'fontsize',12,...
'Backgroundcolor', 'w',...
'String','Number of Periods');

v2=uicontrol('Style','edit',... % creates a bar for the Number of Periods
'Units','normalized',...
'Backgroundcolor', '#808080',...
'Position',[0.33 0.41 0.051 0.03],...
'String',' ',...
'tag','first');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

uicontrol('Style','text',...% creates a text for the frequency
'Units','normalized',...
'Position',[0.01 0.40 0.11 0.10],...
'fontweight','bold',...
'fontsize',12,...
'Backgroundcolor', 'w',...
'String','Frequency(hz)');

v3=uicontrol('Style','edit',... % creates a bar for the frequency
'Units','normalized',...
'Backgroundcolor', '#808080',...
'Position',[0.04 0.41 0.051 0.03],...
'String',' ',...
'tag','first');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Style','pushbutton','Units','normalized','Backgroundcolor', '#808080','String','Signal Vo1','Position',[0.01 0.15 0.15 0.1],'Callback',{@sinus1, v1, v2, v3});
uicontrol('Style','pushbutton','Units','normalized','Backgroundcolor', '#808080','String','Signal Vo2','Position',[0.26 0.15 0.15 0.1],'Callback',{@sinus2, v1, v2, v3});
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function sinus1(~, ~, v1, v2, v3)
    Vi = str2double(get(v1, 'String'));
    P = str2double(get(v2, 'String'));
    f = str2double(get(v3, 'String'));
    T = 1 / f;
    t = 0:T/200:P*T;
    Vd = 0.7;

  
    Vo = Vi - Vd;

    sinus = Vi * sin((2 * pi * f * t));
    sinus1 = zeros(size(t)); % Initialize sinus1 as a zero vector

    for i = 1:length(t)
        if mod(t(i), T) < T/2
            sinus1(i) = Vo * sin((2 * pi * f * t(i)));
        else
            sinus1(i) = 0; % Set to zero for the second half of the period
        end
    end

    % Plot both signals on the same graph
    subplot(2,2,2);
    axis equal;
    plot(t, sinus, 'color', 'blue', 'DisplayName', 'Signal Vi');
    hold on;
    plot(t, sinus1, 'color', 'red', 'DisplayName', 'Signal Vout(R)');
    hold off;

    title('Signal Vout and Vi Chronogram');
    xlabel('Time');
    ylabel('Amplitude');
    grid on;
    legend('show');
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function sinus2(~, ~, v1, v2, v3)
    Vi = str2double(get(v1, 'String'));
    P = str2double(get(v2, 'String'));
    f = str2double(get(v3, 'String'));
    T = 1 / f;
    t = 0:T/200:P*T;
    Vd = 0.7;

  
  

    sinus = Vi * sin((2 * pi * f * t));
    sinus1 = zeros(size(t)); % Initialize sinus1 as a zero vector

    for i = 1:length(t)
        if mod(t(i), T) < T/2
            sinus1(i) =Vd;
        else
            sinus1(i) = 0; % Set to zero for the second half of the period
        end
    end

    % Plot both signals on the same graph
    subplot(2,2,4);
    axis equal;
    plot(t, sinus, 'color', 'blue', 'DisplayName', 'Signal Vi');
    hold on;
    plot(t, sinus1, 'color', 'red', 'DisplayName', 'Signal Vout(D)');
    hold off;

    title('Signal Vout and Vi Chronogram');
    xlabel('Time');
    ylabel('Amplitude');
    grid on;
    legend('show');
end
